overrides:
  '@cuberqaq/asuka-ui': link:../../../../Users/28129/AppData/Local/pnpm/global/5/node_modules/@cuberqaq/asuka-ui
  hzengine-core: link:../../../../Users/28129/AppData/Local/pnpm/global/5/node_modules/hzengine-core
